import NextHead from "next/head";

export function Head() {
  return (
    <NextHead>
      <title>n4.gg - Dashboard</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
}
